### ISSUE TITLE
Feature Request: Support multiple channels/users

### ISSUE THREAD

**Issue by deadlydog** [kasunkv/slack-notification#13]
Sometimes we want to post our message to multiple channels or to multiple users. It would great if we could supply a comma-separated list of channels or users and have the message sent to each of them. As it stands currently we would have to add and configure multiple tasks to our build/release. Thanks!

**Comment by kasunkv** [comment]
Thanks @deadlydog for the feedback. This feature will be added to the next release of the task. I'll keep you updated here.

**Comment by kasunkv** [comment]
@deadlydog The requested feature is now released with the version v4.0.10. The task is a major version update so you need to manually update the task in your build and release definitions.

**Comment by deadlydog** [comment]
Awesome, thanks so much for the quick turn around on this 👍

**Comment by kasunkv** [comment]
@deadlydog You are welcome. :) Thanks for using Slack Notification task..
