### ISSUE TITLE
Message field required by VSTS but not required by API

### ISSUE THREAD

**Issue by joshuapoq** [kasunkv/slack-notification#4]
I'm trying to setup our slack messages to be as short and informative as possible.

Using the attachment only I can show whether a build was successful or not and add a title and message here. We can even add a pre-attachment message acting exactly the same as the message field above.

I know that the Slack API does not require this field but I am forced to provide a normal message by VSTS, and therefor cannot make our slack channel easier to read.

Please could you make the main slack message field not-required to allow this as even trying to trick this field isn't working.

**Comment by kasunkv** [comment]
@joshuapoq Noted. Will provide the fix in the upcoming update. Thank you for the feedback :)

**Comment by kasunkv** [comment]
Completed. @joshuapoq The new version is released. Updated the Slack Notification task to v2.0.0. There are some changes in this version and new feature. Please do through the README.md or the Task overview in the VSTS marketplace for more details.

**Comment by joshuapoq** [comment]
Wow incredibly quick! Thank you!
